import React from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const projects = [
  { number: '01', title: 'NextRole', context: 'Independent project · Live and in active development', description: 'A full-stack job search platform I built with React, TypeScript, Node.js, Express, Prisma and PostgreSQL. I developed accessible UI components, job search and filters with URL-based state, forms, authentication and REST API integrations using React Query.', tags: ['React', 'TypeScript', 'Node.js', 'PostgreSQL'], github: 'https://github.com/neda-jahadi/Nextrole', demo: 'https://nextrole-alpha.vercel.app/' },
  { number: '02', title: 'Lokalnytt.se', context: 'Hubexo · Client project', description: 'I worked across the customer-facing website and admin panel, refreshed frontend functionality and styling with SCSS and Bootstrap, improved Laravel/MySQL integrations and search, and maintained Python/Scrapy spiders and pipelines that fed the database.', tags: ['Laravel', 'PHP', 'MySQL', 'Python / Scrapy'], demo: 'https://www.lokalnytt.se/' },
  { number: '03', title: 'Fraktkedjan.se', context: 'Hubexo · Client project', description: 'I built reusable React components for a shared design system, documented and visually tested them with Storybook and Chromatic, and translated Figma designs into responsive interfaces styled with SCSS.', tags: ['React', 'Storybook', 'Chromatic', 'SCSS'], demo: 'https://www.fraktkedjan.se/' },
];

function App() {
  return <>
    <header className="topbar wrap"><a className="brand" href="#top" aria-label="Neda Jahadi, back to top"><img src="/logo.svg" width="44" height="44" alt=""/><span>Neda Jahadi</span></a><nav aria-label="Main navigation"><a href="#work">Work</a><a href="#experience">Experience</a><a href="#education">Education</a><a href="#contact" className="nav-contact">Contact <span aria-hidden="true">↘</span></a></nav></header>
    <main id="top">
      <section className="intro wrap"><div className="intro-label"><span className="line"/> FULL-STACK DEVELOPER · GOTHENBURG</div><div className="hero-grid"><div><h1>From interface<br/>to <em>impact.</em></h1><p className="hero-lede">I’m Neda, a full-stack developer who builds complete web products—from accessible React interfaces to APIs, business logic and data layers. I’ve worked with TypeScript, Node.js/Express and Laravel/MySQL to turn product needs into reliable, maintainable solutions.</p><div className="hero-actions"><a className="project-button filled" href="#work">See selected work <span aria-hidden="true">↘</span></a><a className="project-button" href="#contact">Get in touch <span aria-hidden="true">↘</span></a></div><p className="hero-proof">React & TypeScript · Laravel & MySQL · Node.js & PostgreSQL</p></div><div className="portrait-frame"><img src="/neda.jpg" width="527" height="421" alt="Portrait of Neda Jahadi"/></div></div><div className="hero-rule"/></section>
      <section className="work wrap" id="work"><div className="section-heading"><span className="section-index">01 / SELECTED WORK</span><h2>What I’ve built</h2></div><div className="project-list">{projects.map(project => <article className="project" key={project.number}><div className="project-number">{project.number}</div><div className="project-body"><p className="project-context">{project.context}</p><h3>{project.title}</h3><p className="project-description">{project.description}</p><div className="tags">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div><div className="project-actions">{project.github && <a className="project-button" href={project.github} target="_blank" rel="noopener noreferrer">GitHub repo <span aria-hidden="true">↗</span></a>}<a className="project-button filled" href={project.demo} target="_blank" rel="noopener noreferrer">Live demo <span aria-hidden="true">↗</span></a></div></div></article>)}</div></section>
      <section className="about" id="experience"><div className="wrap about-grid"><div><span className="section-index">02 / EXPERIENCE</span><h2>Built for real products and real users.</h2></div><div><div className="experience-item"><div className="experience-meta"><strong>Hubexo</strong><span>Full-stack Developer · 2023–2026</span></div><p>Built reusable React and TypeScript components for a shared design system, delivered features in Laravel/MySQL applications, and contributed to a Python/Scrapy data solution. Worked with designers and product teams on usability, accessibility and performance.</p></div><div className="experience-item"><div className="experience-meta"><strong>Understandit</strong><span>Frontend Developer · 2021–2022</span></div><p>Developed React applications for clients in agile teams, translating Figma designs into responsive interfaces and collaborating with designers, backend developers and stakeholders.</p></div><p className="experience-note">I like to understand the need behind a feature, make thoughtful technical choices and build solutions others can maintain.</p><a className="text-link" href="https://github.com/neda-jahadi" target="_blank" rel="noopener noreferrer">Explore my GitHub <span aria-hidden="true">↗</span></a></div></div></section>
      <section className="education wrap" id="education"><div className="section-heading"><span className="section-index">03 / EDUCATION</span><h2>Education</h2></div><div className="education-grid"><article><span className="education-type">VOCATIONAL QUALIFICATION · YH</span><h3>Frontend Developer</h3><p className="education-school">EC Utbildning</p><p>Studies in React, Vue, Angular, JavaScript, Node.js, UX principles and web development.</p></article><article><span className="education-type">BACHELOR’S DEGREE</span><h3>Applied Mathematics</h3><p className="education-school">Isfahan University of Technology</p><p>Academic foundation in applied mathematics, with a focus on programming and data structures.</p></article></div><p className="language-note education-languages">Languages: Swedish and English at professional proficiency · Persian native</p></section>
      <section className="contact wrap" id="contact"><span className="section-index">04 / GET IN TOUCH</span><h2>Let’s build something<br/>worth using.</h2><p className="contact-lede">Looking for a full-stack developer who cares about the product as well as the code? I’d be glad to talk.</p><a className="email" href="mailto:jahadi.neda@gmail.com">jahadi.neda@gmail.com <span aria-hidden="true">↗</span></a><div className="contact-links"><a href="https://github.com/neda-jahadi" target="_blank" rel="noopener noreferrer">GitHub ↗</a></div></section>
    </main><footer className="footer wrap"><span>© {new Date().getFullYear()} Neda Jahadi</span><span>Full-stack developer · Gothenburg, Sweden</span></footer>
  </>;
}

createRoot(document.getElementById('root')).render(<App />);
