import React from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const projects = [
  { number: '01', title: 'NextRole', context: 'Independent project · Live and in active development', description: 'A full-stack job search platform I built with React, TypeScript, Node.js, Express, Prisma and PostgreSQL. I developed accessible UI components, job search and filters with URL-based state, forms, authentication and REST API integrations using React Query.', tags: ['React', 'TypeScript', 'Node.js', 'PostgreSQL'], github: 'https://github.com/neda-jahadi/Nextrole', demo: 'https://nextrole-alpha.vercel.app/' },
  { number: '02', title: 'Lokalnytt.se', context: 'Hubexo · Client project', description: 'I worked across the customer-facing website and admin panel, refreshed frontend functionality and styling with SCSS and Bootstrap, improved Laravel/MySQL integrations and search, and maintained Python/Scrapy spiders and pipelines that fed the database.', tags: ['Laravel', 'PHP', 'MySQL', 'Python / Scrapy'], demo: 'https://www.lokalnytt.se/' },
  { number: '03', title: 'Fraktkedjan.se', context: 'Hubexo · Client project', description: 'I built reusable React components for a shared design system, documented and visually tested them with Storybook and Chromatic, and translated Figma designs into responsive interfaces styled with SCSS.', tags: ['React', 'Storybook', 'Chromatic', 'SCSS'], demo: 'https://www.fraktkedjan.se/' },
];

function App() {
  return <>
    <header className="topbar wrap"><a className="monogram" href="#top" aria-label="Neda Jahadi, back to top">NJ</a><nav aria-label="Main navigation"><a href="#work">Work</a><a href="#about">About</a><a href="mailto:jahadi.neda@gmail.com" className="nav-contact">Contact <span aria-hidden="true">↗</span></a></nav></header>
    <main id="top">
      <section className="intro wrap"><div className="intro-label"><span className="line"/> FULL-STACK DEVELOPER · GOTHENBURG</div><div className="hero-grid"><div><h1>Interfaces built<br/>with <em>care.</em></h1><p className="hero-lede">I’m Neda Jahadi. I build accessible web applications with React, Next.js and TypeScript, and connect them to backend services with Node.js, Express and Laravel.</p><a className="text-link" href="#work">Explore my work <span aria-hidden="true">↘</span></a></div><div className="portrait-frame"><img src="/neda.jpg" width="527" height="421" alt="Portrait of Neda Jahadi"/></div></div><div className="hero-rule"/></section>
      <section className="work wrap" id="work"><div className="section-heading"><span className="section-index">01 / SELECTED WORK</span><h2>What I’ve built</h2></div><div className="project-list">{projects.map(project => <article className="project" key={project.number}><div className="project-number">{project.number}</div><div className="project-body"><p className="project-context">{project.context}</p><h3>{project.title}</h3><p className="project-description">{project.description}</p><div className="tags">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div><div className="project-actions">{project.github && <a className="project-button" href={project.github} target="_blank" rel="noopener noreferrer">GitHub repo <span aria-hidden="true">↗</span></a>}<a className="project-button filled" href={project.demo} target="_blank" rel="noopener noreferrer">Live demo <span aria-hidden="true">↗</span></a></div></div></article>)}</div></section>
      <section className="about" id="about"><div className="wrap about-grid"><div><span className="section-index">02 / ABOUT</span><h2>Product thinking meets full-stack craft.</h2></div><div><p>At Hubexo, I developed end-to-end features across React interfaces, REST APIs and Laravel/MySQL applications. I also contributed to a Python/Scrapy solution for structuring data from external sources, and worked on accessibility, usability and performance in customer-facing products.</p><p>Previously at Understandit, I developed React applications in agile teams and collaborated with designers, backend developers and stakeholders. I have a vocational qualification in frontend development and a bachelor’s degree in applied mathematics, with a focus on programming and data structures.</p><p className="language-note">Swedish and English: professional proficiency · Persian: native</p><a className="text-link" href="https://github.com/neda-jahadi" target="_blank" rel="noopener noreferrer">Explore my GitHub <span aria-hidden="true">↗</span></a></div></div></section>
      <section className="contact wrap"><span className="section-index">03 / GET IN TOUCH</span><h2>Let’s talk about<br/>your product.</h2><a className="email" href="mailto:jahadi.neda@gmail.com">jahadi.neda@gmail.com <span aria-hidden="true">↗</span></a></section>
    </main><footer className="footer wrap"><span>© {new Date().getFullYear()} Neda Jahadi</span><span>Full-stack developer · Gothenburg, Sweden</span></footer>
  </>;
}

createRoot(document.getElementById('root')).render(<App />);
