import React from 'react';
import { createRoot } from 'react-dom/client';
import './style.css';

const projects = [
  { number: '01', title: 'NextRole', context: 'Independent project · Live and in active development', description: 'A full-stack job search platform I built with React, TypeScript, Node.js, Express, Prisma and PostgreSQL. I developed accessible UI components, job search and filters with URL-based state, forms, authentication and REST API integrations using React Query.', tags: ['React', 'TypeScript', 'Node.js', 'PostgreSQL'], github: 'https://github.com/neda-jahadi/Nextrole', demo: 'https://nextrole-alpha.vercel.app/' },
  { number: '02', title: 'Lokalnytt.se', context: 'Hubexo · Client project', description: 'I worked across the customer-facing website and admin panel, refreshed frontend functionality and styling with SCSS and Bootstrap, improved Laravel/MySQL integrations and search, and maintained Python/Scrapy spiders and pipelines that fed the database.', tags: ['Laravel', 'PHP', 'MySQL', 'Python / Scrapy'], demo: 'https://www.lokalnytt.se/' },
  { number: '03', title: 'Fraktkedjan.se', context: 'Hubexo · Client project', description: 'I built reusable React components for a shared design system, documented and visually tested them with Storybook and Chromatic, and translated Figma designs into responsive interfaces styled with SCSS.', tags: ['React', 'Storybook', 'Chromatic', 'SCSS'], demo: 'https://www.fraktkedjan.se/' },
];

function App() {
  return <>
    <header className="topbar wrap"><a className="brand" href="#top" aria-label="Neda Jahadi, back to top"><img src="/logo.svg" width="44" height="44" alt=""/><span>Neda Jahadi</span></a><nav aria-label="Main navigation"><a href="#work">Work</a><a href="#about">About</a><a href="#contact" className="nav-contact">Contact <span aria-hidden="true">↘</span></a></nav></header>
    <main id="top">
      <section className="intro wrap"><div className="intro-label"><span className="line"/> FULL-STACK DEVELOPER · GOTHENBURG</div><div className="hero-grid"><div><h1>Interfaces built<br/>with <em>care.</em></h1><p className="hero-lede">I’m Neda, a full-stack developer in Gothenburg. I build accessible web applications with React and TypeScript, and work across APIs and backend services to turn product needs into complete, maintainable solutions.</p><a className="text-link" href="#work">Explore my work <span aria-hidden="true">↘</span></a></div><div className="portrait-frame"><img src="/neda.jpg" width="527" height="421" alt="Portrait of Neda Jahadi"/></div></div><div className="hero-rule"/></section>
      <section className="work wrap" id="work"><div className="section-heading"><span className="section-index">01 / SELECTED WORK</span><h2>What I’ve built</h2></div><div className="project-list">{projects.map(project => <article className="project" key={project.number}><div className="project-number">{project.number}</div><div className="project-body"><p className="project-context">{project.context}</p><h3>{project.title}</h3><p className="project-description">{project.description}</p><div className="tags">{project.tags.map(tag => <span key={tag}>{tag}</span>)}</div><div className="project-actions">{project.github && <a className="project-button" href={project.github} target="_blank" rel="noopener noreferrer">GitHub repo <span aria-hidden="true">↗</span></a>}<a className="project-button filled" href={project.demo} target="_blank" rel="noopener noreferrer">Live demo <span aria-hidden="true">↗</span></a></div></div></article>)}</div></section>
      <section className="about" id="about"><div className="wrap about-grid"><div><span className="section-index">02 / ABOUT</span><h2>Product thinking meets full-stack craft.</h2></div><div><p>At Hubexo, I worked across React interfaces, Laravel/MySQL applications and a Python/Scrapy data solution. I built reusable components, delivered full-stack features and collaborated closely with designers and product teams.</p><p>Earlier at Understandit, I developed React applications for clients in agile teams. Across both roles, I’ve learned to look beyond the code: understand the user’s need, make thoughtful technical choices and build solutions that others can maintain. I also have a frontend development qualification and a bachelor’s degree in applied mathematics.</p><p className="language-note">Swedish and English: professional proficiency · Persian: native</p><a className="text-link" href="https://github.com/neda-jahadi" target="_blank" rel="noopener noreferrer">Explore my GitHub <span aria-hidden="true">↗</span></a></div></div></section>
      <section className="contact wrap" id="contact"><span className="section-index">03 / GET IN TOUCH</span><h2>Let’s talk about<br/>your product.</h2><a className="email" href="mailto:jahadi.neda@gmail.com">jahadi.neda@gmail.com <span aria-hidden="true">↗</span></a></section>
    </main><footer className="footer wrap"><span>© {new Date().getFullYear()} Neda Jahadi</span><span>Full-stack developer · Gothenburg, Sweden</span></footer>
  </>;
}

createRoot(document.getElementById('root')).render(<App />);
